services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    versions: ['1.3.0']
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

grids:
    webmercator:
        base: GLOBAL_WEBMERCATOR

globals:
  image:
    paletted: false
